---
# Molecule configuration for os_hardening role
# Tests role deployment in Docker containers

dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: docker

platforms:
  # Ubuntu 22.04 for Linux testing
  - name: ubuntu-22.04
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd-cgroups-agent
    environment:
      container: docker
      ANSIBLE_EXTRA_VARS: "{}"
    networks:
      - name: default
        ipv4_config:
          gateway: 172.17.0.1
          subnet: 172.17.0.0/16

  # Debian 11 for additional Linux variant
  - name: debian-11
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    privileged: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd-cgroups-agent
    environment:
      container: docker
      ANSIBLE_EXTRA_VARS: "{}"

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  options:
    vv: true
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy

verifier:
  name: testinfra
  options:
    v: true
  lint:
    name: flake8
